version: '3.8'  
services:  
  elasticsearch:  
    image: elasticsearch:7.10.0  
    environment:  
      - discovery.type=single-node  
      - ES_JAVA_OPTS=-Xms512m -Xmx512m  
    ports:  
      - "9200:9200"  
  metricbeat:  
    image: docker.elastic.co/beats/metricbeat:7.10.0  
    environment:  
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200  
    volumes:  
      - /var/run/docker.sock:/var/run/docker.sock  
    depends_on:  
      - elasticsearch  
    ports:  
      - "5066:5066"  
